[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = '0.6.12'

[dependencies]
stablecoin-evm = { git = "https://github.com/circlefin/stablecoin-evm.git", version = "1.0.0" }
"@openzeppelin-contracts" = "3.4.2"
