[build-system]
requires = [
	"setuptools>=61",
	"wheel",
	"cffi>=1.15.0",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
	"ignore:The 'warn' method is deprecated:DeprecationWarning"
]
